### ISSUE TITLE
For - In loop over Array

### ISSUE THREAD

**Issue by jonryser** [aramk/CSSJSON#19]
In line 124:
`for (i in bits) {`

The for in loop is iterating over an Array. This sometimes breaks depending on the Array passed. This should be changed to a for loop:

`for (var i = 0; i < bits.length; i++) {`

We have changed this in the app we are using, but it forced us to make a copy of your script with the change. It would be fabulous if you could incorporate this fix in your code so that we can keep using your script. We tried to make a branch to submit a Pull Request, but didn't have permission to do so.

Cheers,
Jon

**Comment by aramk** [comment]
Thanks, I've made the change. The code is pretty crappy since I wrote this 6 years ago... I'm shadowing variables as well. Plus some tests would be a plus.
