### ISSUE TITLE
[Feature Request] Typescript Support for this Library

### ISSUE THREAD

**Issue by KRTirtho** [aramk/CSSJSON#24]
Seems like this library has no definitely-typed package or type declaration. So, will typescript type declaration come out in future?
Now, typescript is really getting adopted in a great number so typescript support is really needed. Hope you release a definitely-typed repo or a direct typescript `index.d.ts` in this repo with `types` field pointing to that declaration file in `package.json`.

**Comment by johndcarmichael** [comment]
https://github.com/aramk/CSSJSON/pull/25

**Comment by j-d-carmichael** [comment]
The PR still has not been released to NPM yet though

**Comment by j-d-carmichael** [comment]
I'm not getting a reply from the author of this repo so published under a new name, i use this in my app and installing via github is not appropriate:

https://www.npmjs.com/package/css-convert-json

**Comment by KRTirtho** [comment]
Great to hear from ya! 
Thanks for taking forward this project

I'm closing this issue since a better & maintained version of this same package is now available
